// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package agentsdb

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO agent_runs (
  id,
  tenant_id,
  definition_id,
  trigger,
  goals,
  requested_capabilities,
  status,
  requires_approval
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, tenant_id, definition_id, trigger, goals, requested_capabilities, status, requires_approval, requested_at, last_transition_at
`

type CreateRunParams struct {
	ID                    string
	TenantID              string
	DefinitionID          string
	Trigger               string
	Goals                 []byte
	RequestedCapabilities []byte
	Status                string
	RequiresApproval      bool
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.TenantID,
		arg.DefinitionID,
		arg.Trigger,
		arg.Goals,
		arg.RequestedCapabilities,
		arg.Status,
		arg.RequiresApproval,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DefinitionID,
		&i.Trigger,
		&i.Goals,
		&i.RequestedCapabilities,
		&i.Status,
		&i.RequiresApproval,
		&i.RequestedAt,
		&i.LastTransitionAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, tenant_id, definition_id, trigger, goals, requested_capabilities, status, requires_approval, requested_at, last_transition_at
FROM agent_runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DefinitionID,
		&i.Trigger,
		&i.Goals,
		&i.RequestedCapabilities,
		&i.Status,
		&i.RequiresApproval,
		&i.RequestedAt,
		&i.LastTransitionAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, tenant_id, definition_id, trigger, goals, requested_capabilities, status, requires_approval, requested_at, last_transition_at
FROM agent_runs
WHERE tenant_id = $1
ORDER BY requested_at DESC
`

func (q *Queries) ListRuns(ctx context.Context, tenantID string) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listRuns, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DefinitionID,
			&i.Trigger,
			&i.Goals,
			&i.RequestedCapabilities,
			&i.Status,
			&i.RequiresApproval,
			&i.RequestedAt,
			&i.LastTransitionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
