// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modelgateway.sql

package modelgatewaydb

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT "tenantId", provider, COALESCE("encryptedApiKey", '') AS encrypted_api_key, "modelId", COALESCE("baseUrl", '') AS base_url, "maxTokensPerRequest", "dailyRequestLimit", enabled
FROM "TenantAiConfig"
WHERE "tenantId" = $1
`

type GetConfigRow struct {
	TenantId            string
	Provider            string
	EncryptedApiKey     string
	ModelId             string
	BaseUrl             string
	MaxTokensPerRequest int32
	DailyRequestLimit   int32
	Enabled             bool
}

func (q *Queries) GetConfig(ctx context.Context, tenantID string) (GetConfigRow, error) {
	row := q.db.QueryRow(ctx, getConfig, tenantID)
	var i GetConfigRow
	err := row.Scan(
		&i.TenantId,
		&i.Provider,
		&i.EncryptedApiKey,
		&i.ModelId,
		&i.BaseUrl,
		&i.MaxTokensPerRequest,
		&i.DailyRequestLimit,
		&i.Enabled,
	)
	return i, err
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO "TenantAiConfig" (
  id,
  "tenantId",
  provider,
  "encryptedApiKey",
  "apiKeyIV",
  "apiKeyTag",
  "modelId",
  "baseUrl",
  "maxTokensPerRequest",
  "dailyRequestLimit",
  enabled,
  "createdAt",
  "updatedAt"
) VALUES (
  $1,
  $2,
  $3,
  NULLIF($4, ''),
  NULLIF($5, ''),
  NULLIF($6, ''),
  $7,
  NULLIF($8, ''),
  $9,
  $10,
  $11,
  now(),
  now()
)
ON CONFLICT ("tenantId") DO UPDATE SET
  provider = EXCLUDED.provider,
  "encryptedApiKey" = EXCLUDED."encryptedApiKey",
  "apiKeyIV" = EXCLUDED."apiKeyIV",
  "apiKeyTag" = EXCLUDED."apiKeyTag",
  "modelId" = EXCLUDED."modelId",
  "baseUrl" = EXCLUDED."baseUrl",
  "maxTokensPerRequest" = EXCLUDED."maxTokensPerRequest",
  "dailyRequestLimit" = EXCLUDED."dailyRequestLimit",
  enabled = EXCLUDED.enabled,
  "updatedAt" = now()
RETURNING "tenantId", provider, COALESCE("encryptedApiKey", '') AS encrypted_api_key, "modelId", COALESCE("baseUrl", '') AS base_url, "maxTokensPerRequest", "dailyRequestLimit", enabled
`

type UpsertConfigParams struct {
	ID                  string
	TenantID            string
	Provider            string
	EncryptedApiKey     interface{}
	ApiKeyIv            interface{}
	ApiKeyTag           interface{}
	ModelID             string
	BaseUrl             interface{}
	MaxTokensPerRequest int32
	DailyRequestLimit   int32
	Enabled             bool
}

type UpsertConfigRow struct {
	TenantId            string
	Provider            string
	EncryptedApiKey     string
	ModelId             string
	BaseUrl             string
	MaxTokensPerRequest int32
	DailyRequestLimit   int32
	Enabled             bool
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (UpsertConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertConfig,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.EncryptedApiKey,
		arg.ApiKeyIv,
		arg.ApiKeyTag,
		arg.ModelID,
		arg.BaseUrl,
		arg.MaxTokensPerRequest,
		arg.DailyRequestLimit,
		arg.Enabled,
	)
	var i UpsertConfigRow
	err := row.Scan(
		&i.TenantId,
		&i.Provider,
		&i.EncryptedApiKey,
		&i.ModelId,
		&i.BaseUrl,
		&i.MaxTokensPerRequest,
		&i.DailyRequestLimit,
		&i.Enabled,
	)
	return i, err
}

const upsertConfigPreserveKey = `-- name: UpsertConfigPreserveKey :one
INSERT INTO "TenantAiConfig" (
  id,
  "tenantId",
  provider,
  "modelId",
  "baseUrl",
  "maxTokensPerRequest",
  "dailyRequestLimit",
  enabled,
  "createdAt",
  "updatedAt"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  NULLIF($5, ''),
  $6,
  $7,
  $8,
  now(),
  now()
)
ON CONFLICT ("tenantId") DO UPDATE SET
  provider = EXCLUDED.provider,
  "modelId" = EXCLUDED."modelId",
  "baseUrl" = EXCLUDED."baseUrl",
  "maxTokensPerRequest" = EXCLUDED."maxTokensPerRequest",
  "dailyRequestLimit" = EXCLUDED."dailyRequestLimit",
  enabled = EXCLUDED.enabled,
  "updatedAt" = now()
RETURNING "tenantId", provider, COALESCE("encryptedApiKey", '') AS encrypted_api_key, "modelId", COALESCE("baseUrl", '') AS base_url, "maxTokensPerRequest", "dailyRequestLimit", enabled
`

type UpsertConfigPreserveKeyParams struct {
	ID                  string
	TenantID            string
	Provider            string
	ModelID             string
	BaseUrl             interface{}
	MaxTokensPerRequest int32
	DailyRequestLimit   int32
	Enabled             bool
}

type UpsertConfigPreserveKeyRow struct {
	TenantId            string
	Provider            string
	EncryptedApiKey     string
	ModelId             string
	BaseUrl             string
	MaxTokensPerRequest int32
	DailyRequestLimit   int32
	Enabled             bool
}

func (q *Queries) UpsertConfigPreserveKey(ctx context.Context, arg UpsertConfigPreserveKeyParams) (UpsertConfigPreserveKeyRow, error) {
	row := q.db.QueryRow(ctx, upsertConfigPreserveKey,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.ModelID,
		arg.BaseUrl,
		arg.MaxTokensPerRequest,
		arg.DailyRequestLimit,
		arg.Enabled,
	)
	var i UpsertConfigPreserveKeyRow
	err := row.Scan(
		&i.TenantId,
		&i.Provider,
		&i.EncryptedApiKey,
		&i.ModelId,
		&i.BaseUrl,
		&i.MaxTokensPerRequest,
		&i.DailyRequestLimit,
		&i.Enabled,
	)
	return i, err
}
