// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package memorydb

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO memory_items (
  id,
  namespace_key,
  content,
  summary,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, namespace_key, content, summary, metadata, created_at
`

type CreateItemParams struct {
	ID           string
	NamespaceKey string
	Content      string
	Summary      string
	Metadata     []byte
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (MemoryItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.NamespaceKey,
		arg.Content,
		arg.Summary,
		arg.Metadata,
	)
	var i MemoryItem
	err := row.Scan(
		&i.ID,
		&i.NamespaceKey,
		&i.Content,
		&i.Summary,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, namespace_key, content, summary, metadata, created_at
FROM memory_items
WHERE namespace_key = $1
ORDER BY created_at ASC
`

func (q *Queries) ListItems(ctx context.Context, namespaceKey string) ([]MemoryItem, error) {
	rows, err := q.db.Query(ctx, listItems, namespaceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryItem
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceKey,
			&i.Content,
			&i.Summary,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, namespace_key, tenant_id, scope, principal_id, agent_id, run_id, workflow_id, memory_type, name, created_at, updated_at
FROM memory_namespaces
WHERE tenant_id = $1
ORDER BY scope ASC, memory_type ASC, name ASC
`

func (q *Queries) ListNamespaces(ctx context.Context, tenantID string) ([]MemoryNamespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryNamespace
	for rows.Next() {
		var i MemoryNamespace
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceKey,
			&i.TenantID,
			&i.Scope,
			&i.PrincipalID,
			&i.AgentID,
			&i.RunID,
			&i.WorkflowID,
			&i.MemoryType,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNamespace = `-- name: UpsertNamespace :one
INSERT INTO memory_namespaces (
  id,
  namespace_key,
  tenant_id,
  scope,
  principal_id,
  agent_id,
  run_id,
  workflow_id,
  memory_type,
  name
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (namespace_key) DO UPDATE SET
  updated_at = now()
RETURNING id, namespace_key, tenant_id, scope, principal_id, agent_id, run_id, workflow_id, memory_type, name, created_at, updated_at
`

type UpsertNamespaceParams struct {
	ID           string
	NamespaceKey string
	TenantID     string
	Scope        string
	PrincipalID  string
	AgentID      string
	RunID        string
	WorkflowID   string
	MemoryType   string
	Name         string
}

func (q *Queries) UpsertNamespace(ctx context.Context, arg UpsertNamespaceParams) (MemoryNamespace, error) {
	row := q.db.QueryRow(ctx, upsertNamespace,
		arg.ID,
		arg.NamespaceKey,
		arg.TenantID,
		arg.Scope,
		arg.PrincipalID,
		arg.AgentID,
		arg.RunID,
		arg.WorkflowID,
		arg.MemoryType,
		arg.Name,
	)
	var i MemoryNamespace
	err := row.Scan(
		&i.ID,
		&i.NamespaceKey,
		&i.TenantID,
		&i.Scope,
		&i.PrincipalID,
		&i.AgentID,
		&i.RunID,
		&i.WorkflowID,
		&i.MemoryType,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
