// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orchestration.sql

package orchestrationdb

import (
	"context"
)

const getConnection = `-- name: GetConnection :one
SELECT id, name, kind, scope, endpoint, namespace, labels, capabilities
FROM orchestrator_connections
WHERE name = $1
`

type GetConnectionRow struct {
	ID           string
	Name         string
	Kind         string
	Scope        string
	Endpoint     string
	Namespace    string
	Labels       []byte
	Capabilities []byte
}

func (q *Queries) GetConnection(ctx context.Context, name string) (GetConnectionRow, error) {
	row := q.db.QueryRow(ctx, getConnection, name)
	var i GetConnectionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Scope,
		&i.Endpoint,
		&i.Namespace,
		&i.Labels,
		&i.Capabilities,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, name, kind, scope, endpoint, namespace, labels, capabilities
FROM orchestrator_connections
ORDER BY name ASC
`

type ListConnectionsRow struct {
	ID           string
	Name         string
	Kind         string
	Scope        string
	Endpoint     string
	Namespace    string
	Labels       []byte
	Capabilities []byte
}

func (q *Queries) ListConnections(ctx context.Context) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsRow
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Scope,
			&i.Endpoint,
			&i.Namespace,
			&i.Labels,
			&i.Capabilities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnection = `-- name: UpsertConnection :one
INSERT INTO orchestrator_connections (
  id,
  name,
  kind,
  scope,
  endpoint,
  namespace,
  labels,
  capabilities
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
ON CONFLICT (name) DO UPDATE SET
  kind = EXCLUDED.kind,
  scope = EXCLUDED.scope,
  endpoint = EXCLUDED.endpoint,
  namespace = EXCLUDED.namespace,
  labels = EXCLUDED.labels,
  capabilities = EXCLUDED.capabilities,
  updated_at = now()
RETURNING id, name, kind, scope, endpoint, namespace, labels, capabilities
`

type UpsertConnectionParams struct {
	ID           string
	Name         string
	Kind         string
	Scope        string
	Endpoint     string
	Namespace    string
	Labels       []byte
	Capabilities []byte
}

type UpsertConnectionRow struct {
	ID           string
	Name         string
	Kind         string
	Scope        string
	Endpoint     string
	Namespace    string
	Labels       []byte
	Capabilities []byte
}

func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (UpsertConnectionRow, error) {
	row := q.db.QueryRow(ctx, upsertConnection,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Scope,
		arg.Endpoint,
		arg.Namespace,
		arg.Labels,
		arg.Capabilities,
	)
	var i UpsertConnectionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Scope,
		&i.Endpoint,
		&i.Namespace,
		&i.Labels,
		&i.Capabilities,
	)
	return i, err
}
