#!/usr/bin/env bash
# Idempotent GitHub label setup for Arsenale project
# Usage: bash scripts/setup-github-labels.sh
#
# Creates or updates all labels used by the task/idea GitHub Issues integration.
# Safe to run multiple times — existing labels are updated, not duplicated.

set -euo pipefail

REPO="dnviti/arsenale"

echo "Setting up GitHub labels for $REPO..."

# Source identifier
gh label create "claude-code"       --repo "$REPO" --color "6f42c1" --description "Generated by Claude Code"          --force

# Issue type
gh label create "task"              --repo "$REPO" --color "0075ca" --description "Task issue"                         --force
gh label create "idea"              --repo "$REPO" --color "e8d44d" --description "Idea proposal"                      --force

# Priority
gh label create "priority:high"     --repo "$REPO" --color "d73a4a" --description "ALTA priority"                      --force
gh label create "priority:medium"   --repo "$REPO" --color "fbca04" --description "MEDIA priority"                     --force
gh label create "priority:low"      --repo "$REPO" --color "0e8a16" --description "BASSA priority"                     --force

# Status
gh label create "status:todo"         --repo "$REPO" --color "cfd3d7" --description "Pending"                          --force
gh label create "status:in-progress"  --repo "$REPO" --color "1d76db" --description "In progress"                      --force
gh label create "status:done"         --repo "$REPO" --color "0e8a16" --description "Completed"                        --force

# Sections
gh label create "section:core"          --repo "$REPO" --color "bfdadc" --description "Section A — Core Features"              --force
gh label create "section:suggested"     --repo "$REPO" --color "c5def5" --description "Section B — Additional Suggested"       --force
gh label create "section:multi-tenant"  --repo "$REPO" --color "d4c5f9" --description "Section C — Multi-Tenant/Teams"         --force
gh label create "section:multi-backend" --repo "$REPO" --color "f9d0c4" --description "Section D — Multi-Backend/Gateway"      --force
gh label create "section:zero-trust"    --repo "$REPO" --color "e99695" --description "Section E — Zero Trust Hardening"       --force
gh label create "section:keychain"      --repo "$REPO" --color "fef2c0" --description "Section F — Password Keychain/Vault"    --force
gh label create "section:orchestration" --repo "$REPO" --color "bfe5bf" --description "Section G — Gateway Orchestration"      --force
gh label create "section:scouted"       --repo "$REPO" --color "d4c5f9" --description "Section H — Scouted Features"             --force
gh label create "section:sso"           --repo "$REPO" --color "f9d0c4" --description "Section I — SSO & Domain Credential"      --force

echo ""
echo "Done! All labels created/updated for $REPO."
echo "Verify with: gh label list --repo $REPO"
